# Form implementation generated from reading ui file '边框重写.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 720)
        Form.setMouseTracking(False)
        Form.setTabletTracking(True)
        Form.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        Form.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        Form.setAcceptDrops(True)
        Form.setWindowTitle("Free my WW")
        self.GlobleLayout = QtWidgets.QVBoxLayout(Form)
        self.GlobleLayout.setContentsMargins(9, -1, -1, -1)
        self.GlobleLayout.setObjectName("GlobleLayout")
        self.LabelLayout = QtWidgets.QHBoxLayout()
        self.LabelLayout.setObjectName("LabelLayout")
        self.LabelPic = QtWidgets.QLabel(parent=Form)
        self.LabelPic.setObjectName("LabelPic")
        self.LabelLayout.addWidget(self.LabelPic)
        self.SoftwareName = QtWidgets.QLabel(parent=Form)
        self.SoftwareName.setObjectName("SoftwareName")
        self.LabelLayout.addWidget(self.SoftwareName)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.LabelLayout.addItem(spacerItem)
        self.HideToWindow = QtWidgets.QPushButton(parent=Form)
        self.HideToWindow.setObjectName("HideToWindow")
        self.LabelLayout.addWidget(self.HideToWindow)
        self.MinToSys = QtWidgets.QPushButton(parent=Form)
        self.MinToSys.setObjectName("MinToSys")
        self.LabelLayout.addWidget(self.MinToSys)
        self.Min = QtWidgets.QPushButton(parent=Form)
        self.Min.setObjectName("Min")
        self.LabelLayout.addWidget(self.Min)
        self.MaxOrRestore = QtWidgets.QPushButton(parent=Form)
        self.MaxOrRestore.setObjectName("MaxOrRestore")
        self.LabelLayout.addWidget(self.MaxOrRestore)
        self.Close = QtWidgets.QPushButton(parent=Form)
        self.Close.setObjectName("Close")
        self.LabelLayout.addWidget(self.Close)
        self.GlobleLayout.addLayout(self.LabelLayout)
        self.MainLayout = QtWidgets.QVBoxLayout()
        self.MainLayout.setObjectName("MainLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(parent=self.tab)
        self.label.setGeometry(QtCore.QRect(300, 150, 631, 291))
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.MainLayout.addWidget(self.tabWidget)
        self.GlobleLayout.addLayout(self.MainLayout)
        self.GlobleLayout.setStretch(0, 1)
        self.GlobleLayout.setStretch(1, 20)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.LabelPic.setText(_translate("Form", "图标"))
        self.SoftwareName.setText(_translate("Form", "软件名字版本号"))
        self.HideToWindow.setText(_translate("Form", "完全隐藏"))
        self.MinToSys.setText(_translate("Form", "系统托盘"))
        self.Min.setText(_translate("Form", "最小化"))
        self.MaxOrRestore.setText(_translate("Form", "最大化/恢复"))
        self.Close.setText(_translate("Form", "关闭"))
        self.label.setText(_translate("Form", "你好"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Tab 2"))
