# Form implementation generated from reading ui file 'logic.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from math import degrees
from wsgiref.util import application_uri
from PyQt6 import QtCore, QtGui, QtWidgets
# from PyQt6.QtWidgets import QApplication, QMainWindow, QWidget
# import sys


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(891, 641)
        self.account = QtWidgets.QLabel(parent=Form)
        self.account.setGeometry(QtCore.QRect(130, 170, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        font.setBold(True)
        self.account.setFont(font)
        self.account.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.account.setObjectName("account")
        self.counter_input = QtWidgets.QLineEdit(parent=Form)
        self.counter_input.setGeometry(QtCore.QRect(210, 170, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        self.counter_input.setFont(font)
        self.counter_input.setObjectName("counter_input")
        self.password = QtWidgets.QLabel(parent=Form)
        self.password.setGeometry(QtCore.QRect(130, 220, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        font.setBold(True)
        self.password.setFont(font)
        self.password.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.password.setObjectName("password")
        self.password_input = QtWidgets.QLineEdit(parent=Form)
        self.password_input.setGeometry(QtCore.QRect(210, 220, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        self.password_input.setFont(font)
        self.password_input.setObjectName("password_input")
        self.login = QtWidgets.QPushButton(parent=Form)
        self.login.setGeometry(QtCore.QRect(130, 290, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        font.setBold(False)
        self.login.setFont(font)
        self.login.setObjectName("login")
        self.cannel_login = QtWidgets.QPushButton(parent=Form)
        self.cannel_login.setGeometry(QtCore.QRect(360, 290, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        font.setBold(False)
        self.cannel_login.setFont(font)
        self.cannel_login.setObjectName("cannel_login")
        self.login_status = QtWidgets.QTextBrowser(parent=Form)
        self.login_status.setGeometry(QtCore.QRect(520, 170, 301, 161))
        self.login_status.setObjectName("login_status")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.account.setText(_translate("Form", "账号"))
        self.password.setText(_translate("Form", "密码"))
        self.login.setText(_translate("Form", "登录"))
        self.cannel_login.setText(_translate("Form", "取消"))

# if __name__ == '__main__':
#     # app = QApplication(sys.argv)
#     # # win = Ui_Form()
#     # mywin = win.setupUi()
