# Form implementation generated from reading ui file 'Free_my_WW_UI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 720)
        Form.setMouseTracking(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Logo/256X256.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form.setWindowIcon(icon)
        self.MustLayout = QtWidgets.QVBoxLayout(Form)
        self.MustLayout.setContentsMargins(0, 0, 0, 0)
        self.MustLayout.setSpacing(0)
        self.MustLayout.setObjectName("MustLayout")
        self.GlobalWidget = QtWidgets.QWidget(parent=Form)
        self.GlobalWidget.setMouseTracking(True)
        self.GlobalWidget.setObjectName("GlobalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.GlobalWidget)
        self.verticalLayout.setContentsMargins(5, 0, 5, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TitleBar = QtWidgets.QGridLayout()
        self.TitleBar.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.TitleBar.setContentsMargins(10, -1, -1, -1)
        self.TitleBar.setSpacing(0)
        self.TitleBar.setObjectName("TitleBar")
        self.TitleLayout = QtWidgets.QHBoxLayout()
        self.TitleLayout.setContentsMargins(5, 5, 0, -1)
        self.TitleLayout.setSpacing(0)
        self.TitleLayout.setObjectName("TitleLayout")
        self.LabelPic = QtWidgets.QLabel(parent=self.GlobalWidget)
        self.LabelPic.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.LabelPic.setText("")
        self.LabelPic.setPixmap(QtGui.QPixmap(":/Logo/32X32.ico"))
        self.LabelPic.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.LabelPic.setObjectName("LabelPic")
        self.TitleLayout.addWidget(self.LabelPic)
        self.SoftwareName = QtWidgets.QLabel(parent=self.GlobalWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.SoftwareName.setFont(font)
        self.SoftwareName.setObjectName("SoftwareName")
        self.TitleLayout.addWidget(self.SoftwareName)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.TitleLayout.addItem(spacerItem)
        self.TitleLayout.setStretch(2, 13)
        self.TitleBar.addLayout(self.TitleLayout, 0, 0, 2, 1)
        self.WindowControlButtons = QtWidgets.QHBoxLayout()
        self.WindowControlButtons.setSpacing(0)
        self.WindowControlButtons.setObjectName("WindowControlButtons")
        self.HideToWindow = QtWidgets.QPushButton(parent=self.GlobalWidget)
        self.HideToWindow.setMouseTracking(True)
        self.HideToWindow.setWhatsThis("")
        self.HideToWindow.setStyleSheet("QPushButton {\n"
"    background: transparent;  /* 透明背景 */\n"
"    border: none;            /* 移除默认边框 */\n"
"}\n"
"/* 悬停状态 */\n"
"QPushButton:hover {\n"
"    background: rgb(196, 43, 28); /* 轻微高亮 */\n"
"}\n"
"/* 按下状态 */\n"
"QPushButton:pressed {\n"
"    background: rgb(199, 64, 49);\n"
"}")
        self.HideToWindow.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/标题栏/深度隐藏.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.HideToWindow.setIcon(icon1)
        self.HideToWindow.setIconSize(QtCore.QSize(40, 30))
        self.HideToWindow.setObjectName("HideToWindow")
        self.WindowControlButtons.addWidget(self.HideToWindow)
        self.SystemTray = QtWidgets.QPushButton(parent=self.GlobalWidget)
        self.SystemTray.setMouseTracking(True)
        self.SystemTray.setStatusTip("")
        self.SystemTray.setStyleSheet("QPushButton {\n"
"    background: transparent;  /* 透明背景 */\n"
"    border: none;            /* 移除默认边框 */\n"
"}\n"
"/* 悬停状态 */\n"
"QPushButton:hover {\n"
"    background: rgb(233, 233, 233); /* 轻微高亮 */\n"
"}\n"
"/* 按下状态 */\n"
"QPushButton:pressed {\n"
"    background: rgb(213, 213, 213);\n"
"}")
        self.SystemTray.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/标题栏/托盘隐藏.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.SystemTray.setIcon(icon2)
        self.SystemTray.setIconSize(QtCore.QSize(40, 30))
        self.SystemTray.setObjectName("SystemTray")
        self.WindowControlButtons.addWidget(self.SystemTray)
        self.Min = QtWidgets.QPushButton(parent=self.GlobalWidget)
        self.Min.setMouseTracking(True)
        self.Min.setStyleSheet("QPushButton {\n"
"    background: transparent;  /* 透明背景 */\n"
"    border: none;            /* 移除默认边框 */\n"
"}\n"
"/* 悬停状态 */\n"
"QPushButton:hover {\n"
"    background: rgb(233, 233, 233); /* 轻微高亮 */\n"
"}\n"
"/* 按下状态 */\n"
"QPushButton:pressed {\n"
"    background: rgb(213, 213, 213);\n"
"}")
        self.Min.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/标题栏/最小化.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Min.setIcon(icon3)
        self.Min.setIconSize(QtCore.QSize(40, 30))
        self.Min.setObjectName("Min")
        self.WindowControlButtons.addWidget(self.Min)
        self.MaxOrRestore = QtWidgets.QPushButton(parent=self.GlobalWidget)
        self.MaxOrRestore.setMouseTracking(True)
        self.MaxOrRestore.setStyleSheet("QPushButton {\n"
"    background: transparent;  /* 透明背景 */\n"
"    border: none;            /* 移除默认边框 */\n"
"    icon: url(:/标题栏/最大化.png); /*最大化图标*/\n"
"}\n"
"/* 悬停状态 */\n"
"QPushButton:hover {\n"
"    background: rgb(233, 233, 233); /* 轻微高亮 */\n"
"}\n"
"/* 按下状态 */\n"
"QPushButton:pressed {\n"
"    background: rgb(213, 213, 213);\n"
"}\n"
"/* 选中状态显示*/\n"
"QPushButton:checked {\n"
"    icon: url(:/标题栏/窗口恢复.png);    /*恢复图标*/\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/标题栏/最大化.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.MaxOrRestore.setIcon(icon4)
        self.MaxOrRestore.setIconSize(QtCore.QSize(40, 30))
        self.MaxOrRestore.setCheckable(True)
        self.MaxOrRestore.setChecked(False)
        self.MaxOrRestore.setAutoRepeat(False)
        self.MaxOrRestore.setObjectName("MaxOrRestore")
        self.WindowControlButtons.addWidget(self.MaxOrRestore)
        self.Close = QtWidgets.QPushButton(parent=self.GlobalWidget)
        self.Close.setMouseTracking(True)
        self.Close.setStyleSheet("QPushButton {\n"
"    background: transparent;  /* 透明背景 */\n"
"    border:  transparent;            /* 移除默认边框 */\n"
"}\n"
"/* 悬停状态 */\n"
"QPushButton:hover {\n"
"    background: rgb(196, 43, 28); /* 轻微高亮 */\n"
"}\n"
"/* 按下状态 */\n"
"QPushButton:pressed {\n"
"    background: rgb(199, 64, 49);\n"
"}\n"
"")
        self.Close.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/标题栏/关闭.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Close.setIcon(icon5)
        self.Close.setIconSize(QtCore.QSize(40, 30))
        self.Close.setObjectName("Close")
        self.WindowControlButtons.addWidget(self.Close)
        self.TitleBar.addLayout(self.WindowControlButtons, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.TitleBar)
        self.MainWidget = QtWidgets.QWidget(parent=self.GlobalWidget)
        self.MainWidget.setMouseTracking(True)
        self.MainWidget.setObjectName("MainWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.MainWidget)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.MainWidget)
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout.addWidget(self.MainWidget)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 20)
        self.MustLayout.addWidget(self.GlobalWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.SoftwareName.setText(_translate("Form", "Free my WW 1.0.0"))
        self.HideToWindow.setToolTip(_translate("Form", "深度隐藏（去任务管理器找）"))
        self.SystemTray.setToolTip(_translate("Form", "托盘隐藏"))
        self.Min.setToolTip(_translate("Form", "最小化"))
        self.MaxOrRestore.setToolTip(_translate("Form", "最大化/恢复"))
        self.Close.setToolTip(_translate("Form", "关闭"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Tab 2"))
